---
title: "FaceNewsIntervention - Data Cleaning"
editor: source
editor_options: 
  chunk_output_type: console
format:
  html:
    code-fold: true
    self-contained: true
    toc: true
---


## Data Preparation

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(easystats)
library(patchwork)
library(ggside)
library(modelsummary)
```


```{r}
#| code-fold: false

df <- read.csv("../data/rawdata.csv")

dfmist <- read.csv("../data/rawdata_mist.csv")
```

The initial sample consisted of `r report::report_participants(df, age="Age", gender="Gender", education="Education")`, for a total trial number of `r nrow(df)`.


## Questionnaires

### BFI

```{r}
#| code-fold: false

## this is creating the Big 5 scores out of the BFI data, but currently these are just assigned to random numbers, you'll need to check the questionnaire files to figure out which are which and assign them properly here
df$BFI_Neuroticism <- (df$BFI10_1 + df$BFI10_2) / 2
df$BFI_Extraversion <- (df$BFI10_3 + df$BFI10_4) / 2
```

```{r}
bfi <- select(df, starts_with("BFI_"))

modelsummary::datasummary_skim(bfi)
```


## Intervention

```{r}

```



